#!/usr/bin/env bash

# Notice: There have a problem tmux loadb will set twice

if [[ $1 = "get" ]]; then # get from remote
  pan clipboard __GET__ > ~/.clipboard
elif [[ $1 = "put" ]]; then # get from naive os
  [[ "$OSTYPE" = darwin* ]] && pbpaste > ~/.clipboard
else
  cat - > ~/.clipboard
fi

# 如果存在 pan 命令，就自动上传到 pan 中
test pan && pan clipboard < ~/.clipboard
# 在 tmux 自己的 copy-pipe-and-cancel 命令中，不会去读取 ~/.zshenv 的变量
[[ -n $TMUX ]] && tmux loadb - < ~/.clipboard

[[ "$OSTYPE" = darwin* ]] && pbcopy < ~/.clipboard
