#history max num
export HISTSIZE=100000
#history max save
export SAVEHIST=100000
export EDITOR=vim
# set -o vi #设置shell快捷键的默认快捷键
# Compilation flags
export ARCHFLAGS="-arch x86_64"

### display language
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
# export LC_ALL=
# locale -v

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    # export TERM='xterm-256color'
    # export TERM='screen-256color'
    echo "in ssl connection"
fi

# if in tmux, set TERM
# if [[ -n $TMUX ]]; then
    # export TERM='screen-256color'
# fi

if [[ -n "$ZSH_VERSION" ]]; then
    # zsh plugin manager
    # git clone https://github.com/zsh-users/antigen.git
    export AUTOENV_FILE_ENTER=".env"
    if [[ -s "~/.dotfiles/modules/antigen/antigen.zsh" ]]; then
        source ~/.dotfiles/modules/antigen/antigen.zsh
        antigen bundle Tarrasch/zsh-autoenv
        antigen bundle zsh-users/zsh-syntax-highlighting
        antigen bundle robbyrussell/oh-my-zsh plugins/z
        antigen bundle zsh-users/zsh-autosuggestions
        antigen apply
    fi

    typeset -U PATH
# elif [[ -n "$BASH_VERSION" ]]; then
fi

. ~/.dotfiles/zshrc/zsh_func
. ~/.dotfiles/zshrc/zsh_path
. ~/.dotfiles/zshrc/zsh_aliases
